language: python
python:
  - 2.7
cache:
  - pip
  - apt
before_script:
  - sudo -- sh -c "echo '127.0.0.1  boxoffice.travis.dev' >> /etc/hosts"
  - psql -c 'create database boxoffice_testing;' -U postgres
  - nohup python runtestserver.py &
  - sleep 30
install:
  - pip install -r test_requirements.txt
  - pip install -r requirements.txt
  - npm install casperjs
script:
  - nosetests -v tests
  - casperjs test tests
addons:
  postgresql: "9.4"
services:
  - redis-server
notifications:
  email: false